name: Build and Push Branch

on:
  push:
    branches-ignore:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.ref_name }}
          file: docker/Dockerfile
      - 
        name: Build and push Nvidia
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.ref_name }}-nvidia
          file: docker/Dockerfile-Nvidia